### ISSUE TITLE
subdomains command not working after update to allow user defined configuration file

### ISSUE THREAD

**Issue by sethsec** [sethsec/celerystalk#63]
```./celerystalk subdomains -d sample.com -c config.ini 

celerystalk  -	An asynchronous network enumeration/vulnerability scanner 
    v1.1	Run all your tools against all your hosts (IPs/virtual hosts/subdomains)
		by @sethsec
		Build: 160

Traceback (most recent call last):
  File "./celerystalk", line 943, in <module>
    main(arguments)
  File "./celerystalk", line 754, in main
    lib.scan.create_dns_recon_tasks(arguments["<domains>"], arguments["--simulation"], workspace, output_dir)
  File "/home/ubuntu/proj/celerystalk/lib/scan.py", line 587, in create_dns_recon_tasks
    config, supported_services = config_parser.read_config_ini(config_file)
  File "/home/ubuntu/proj/celerystalk/lib/config_parser.py", line 18, in read_config_ini
    config.read([config_file])
  File "/usr/lib/python2.7/ConfigParser.py", line 302, in read
    fp = open(filename)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by sethsec** [comment]
This should be fixed now.  keeping it open for another day or two to see if anyone else has issues.

**Comment by sethsec** [comment]
Everything looks good. closing
